spring:
  datasource:
    name: articles
    platform: h2
  h2:
    console:
      enabled: true
      path: /console

pvdata:
  articles: articles_data.csv

flyway:
  baseline-on-migrate: true
  enabled: true
  locations: classpath:/db/migration